[package]
name = "doppler"
version = "0.1.0"
authors = ["Tomasz"]
build = "build.rs" # LALRPOP preprocessing

[dependencies]
lalrpop-util = "0.16.0"
regex = "0.2.0"

# Add a build-time dependency on the lalrpop library:
[build-dependencies]
lalrpop = "0.16.0"